name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 Models/

      - name: Run tests
        run: |
          pip install pytest
          pytest    

      - name: Build the Model
        run: |
          python model_training.py

      - name: Build Docker Image
        run: docker build -t assignment-group-52:latest .

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image
        run: |
          docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/app:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/app:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: mlopsAssignment
          images: ${{ secrets.ACR_LOGIN_SERVER }}/app:${{ github.sha }}    

      - name: Upload model as artifact
        uses: actions/upload-artifact@v3
        with:
          name: model-artifact
          path: Models/model.joblib